require "test_helper"

# The brand marks in public/ are generated by script/build_brand_icons.py and
# are referenced by filename from three places that never fail loudly: the
# layout's <link> tags, the PWA manifest, and the manifest's maskable entry.
# A renamed or mis-generated file just quietly stops being an icon.
class BrandIconsTest < ActiveSupport::TestCase
  MANIFEST = "app/views/pwa/manifest.json.erb".freeze

  # Width, height and colour type out of a PNG's IHDR, which is always the
  # first chunk and always at a fixed offset.
  def png_header(path)
    bytes = File.binread(Rails.public_path.join(path), 26)
    assert_equal "\x89PNG\r\n\x1A\n".b, bytes[0, 8], "#{path} is not a PNG"
    { width: bytes[16, 4].unpack1("N"), height: bytes[20, 4].unpack1("N"), color_type: bytes[25].ord }
  end

  test "the manifest renders as JSON and every icon it names exists" do
    manifest = JSON.parse(ApplicationController.render(template: "pwa/manifest", formats: [ :json ]))

    assert_predicate manifest["icons"], :any?
    manifest["icons"].each do |icon|
      assert_path_exists Rails.public_path.join(icon["src"].delete_prefix("/")),
        "the manifest names #{icon['src']}, which is not in public/"
    end
  end

  test "the manifest carries the ledger's colours rather than the scaffold's" do
    manifest = JSON.parse(ApplicationController.render(template: "pwa/manifest", formats: [ :json ]))

    # The Rails scaffold ships "red" for both, matching the red-circle
    # placeholder icon it also ships.
    assert_equal "#4A1219", manifest["theme_color"]
    assert_equal "#F6F2E9", manifest["background_color"]
  end

  test "the maskable icon is a separate file from the plain one" do
    # A maskable icon is cropped to a circle of 80% the width. The plain icon's
    # art clears that circle by about three pixels, which is not a margin, so
    # the two entries must not share a file.
    srcs = JSON.parse(ApplicationController.render(template: "pwa/manifest", formats: [ :json ]))["icons"]
      .group_by { |i| i["purpose"] }
      .transform_values { |icons| icons.map { |i| i["src"] } }

    assert_equal [ "/icon.png" ], srcs["any"]
    assert_equal [ "/icon-maskable.png" ], srcs["maskable"]
  end

  test "the marks are 512 square and carry no alpha channel" do
    # Colour type 2 is RGB with no alpha channel at all. These double as the
    # apple-touch-icon, where a stray alpha channel is a submission error.
    %w[icon.png icon-maskable.png].each do |name|
      assert_equal({ width: 512, height: 512, color_type: 2 }, png_header(name), name)
    end
  end

  test "the layout's icon links resolve" do
    layout = Rails.root.join("app/views/layouts/application.html.erb").read
    hrefs = layout.scan(/<link[^>]*rel="(?:icon|apple-touch-icon)"[^>]*href="([^"]+)"/).flatten

    assert_equal %w[/icon.png /icon.svg /icon.png], hrefs
    hrefs.uniq.each { |href| assert_path_exists Rails.public_path.join(href.delete_prefix("/")) }
  end

  test "the SVG mark carries no active content" do
    # public/icon.svg is served same-origin and is directly navigable, so it
    # must stay pure geometry — no script, no external references.
    svg = Rails.public_path.join("icon.svg").read

    assert_match(/\A<svg/, svg)
    refute_match(/<script|<foreignObject|<image|href=|on\w+=/i, svg)
  end
end
